name: driver_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.1

  # Networking
  dio: ^5.5.0+1
  socket_io_client: ^2.0.3+1

  # Maps & Location
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  permission_handler: ^12.0.1

  # Storage
  flutter_secure_storage: ^9.2.2

  # UI
  cupertino_icons: ^1.0.6
  wakelock_plus: ^1.2.8
  url_launcher: ^6.2.5
  intl: ^0.20.2
  pinput: ^5.0.0
  intl_phone_field: ^3.2.0


  # Background & Notifications
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^18.0.0
  easy_localization: ^3.0.7
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
  fl_chart: ^0.68.0
  # Audio
  audioplayers: ^6.0.0
  image_picker: ^1.0.7
  shared_preferences: ^2.5.4
  android_intent_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo_padded.png
    color: "#FFFFFF"


flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
    - assets/translations/
